#!/bin/sh

# PROVIDE: yacoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# yacoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable yacoin service.
# yacoin_config (path): Set to /usr/local/etc/yacoin.conf by default.
# yacoin_user:  The user account yacoin daemon runs as. It uses 'root' user by default.
# yacoin_group: The group account yacoin daemon runs as. It uses 'wheel' group by default.
# yacoin_datadir (str): Default to "/var/db/yacoin". Base data directory.

. /etc/rc.subr

name=yacoin
rcvar=yacoin_enable

: ${yacoin_enable:=NO}
: ${yacoin_config=/usr/local/etc/yacoin.conf}
: ${yacoin_datadir=/var/db/yacoin}
: ${yacoin_user="root"}
: ${yacoin_group="wheel"}

required_files=${yacoin_config}
command=/usr/local/bin/yacoind
yacoin_chdir=${yacoin_datadir}
pidfile="${yacoin_datadir}/yacoind.pid"
stop_cmd=yacoin_stop
command_args="-conf=${yacoin_config} -datadir=${yacoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

yacoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${yacoin_datadir}
	[ $? -eq 0 ] && chown -R ${yacoin_user}:${yacoin_group} ${yacoin_datadir}
}

yacoin_prestart()
{
	if [ ! -d "${yacoin_datadir}/." ]; then
		yacoin_create_datadir || return 1
	fi
}

yacoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

yacoin_stop()
{
    yacoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${yacoin_config} -datadir=${yacoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
